export const dictionary = {
  artificial: "مصنوعی",
  intelligence: "ذہانت",
  is: "ہے",
  the: "یہ",
  simulation: "نقل",
  of: "کا",
  human: "انسانی",
  in: "میں",
  machines: "مشینیں",
  climate: "آب و ہوا",
  change: "تبدیلی",
  refers: "کہلاتا ہے",
  to: "کو",
  long: "طویل",
  term: "مدتی",
  alterations: "تبدیلیاں",
  weather: "موسم",
  patterns: "پیٹرن",
  caused: "پیدا کردہ",
  by: "کی طرف سے",
  activities: "سرگرمیاں",
  blockchain: "بلاک چین",
  decentralized: "غیر مرکزی",
  digital: "ڈیجیٹل",
  ledger: "رجسٹر",
  used: "استعمال ہوتا ہے",
  for: "کے لیے",
  secure: "محفوظ",
  transactions: "لین دین",
  mental: "ذہنی",
  health: "صحت",
  involves: "شامل ہے",
  emotional: "جذباتی",
  psychological: "نفسیاتی",
  social: "سماجی",
  well: "فلاح",
  being: "بہبود",
  cybersecurity: "سائبر سیکیورٹی",
  protects: "تحفظ کرتا ہے",
  data: "ڈیٹا",
  systems: "نظام",
  from: "سے",
  cyberattacks: "سائبر حملے",
  unauthorized: "غیر مجاز",
  access: "رسائی",
  online: "آن لائن",
  education: "تعلیم",
  provides: "فراہم کرتا ہے",
  flexibility: "لچک",
  learners: "سیکھنے والے",
  using: "استعمال کرتے ہوئے",
  tools: "اوزار",
  internet: "انٹرنیٹ",
  electric: "برقی",
  vehicles: "گاڑیاں",
  use: "استعمال کرتی ہیں",
  electricity: "بجلی",
  instead: "کی بجائے",
  fuel: "ایندھن",
  help: "مدد دیتی ہیں",
  reduce: "کم کرنا",
  pollution: "آلودگی",
  clean: "صاف",
  energy: "توانائی",
  sources: "ذرائع",
  like: "جیسے",
  solar: "شمسی",
  wind: "ہوا",
  environmental: "ماحولیاتی",
  impact: "اثر",
  machine: "مشین",
  learning: "سیکھنا",
  enables: "قابل بناتی ہے",
  computers: "کمپیوٹرز",
  learn: "سیکھتے ہیں",
  improve: "بہتر بناتے ہیں",
  performance: "کارکردگی",
  remote: "ریموٹ",
  work: "کام",
  allows: "اجازت دیتا ہے",
  employees: "ملازمین",
  home: "گھر",
  collaboration: "تعاون",
  ecommerce: "ای کامرس",
  buying: "خریدنا",
  selling: "بیچنا",
  goods: "اشیاء",
  services: "خدمات",
  platforms: "پلیٹ فارمز",
  connect: "جڑنا",
  share: "شیئر کرنا",
  content: "مواد",
  privacy: "پرائیویسی",
  quantum: "کوانٹم",
  computing: "کمپیوٹنگ",
  virtual: "ورچوئل",
  reality: "حقیقت",
  immersive: "دلچسپ",
  augmented: "اضافہ شدہ",
  overlay: "اوورلے",
  fifth: "پانچویں",
  generation: "نسل",
  wireless: "وائرلیس",
  faster: "تیز تر",
  things: "چیزیں",
  iot: "انٹرنیٹ آف تھنگز",
  marketing: "مارکیٹنگ",
  promote: "تشہیر کرنا",
  products: "مصنوعات",
  strategies: "حکمت عملیاں",
  big: "بڑا",
  analyze: "تجزیہ کرنا",
  trends: "رجحانات",
  genetics: "جینیات",
  modify: "ترمیم کرنا",
  dna: "ڈی این اے",
  characteristics: "خصوصیات",
  organisms: "جاندار",
  space: "خلاء",
  exploration: "کھوج",
  travel: "سفر",
  earth: "زمین",
  atmosphere: "فضا",
  renewable: "قابل تجدید",
  resources: "وسائل",
  sunlight: "دھوپ",
  water: "پانی",
  scarcity: "کمی",
  food: "خوراک",
  ensure: "یقینی بنانا",
  safe: "محفوظ",
  nutritious: "غذائیت بخش",
  plastic: "پلاسٹک",
  waste: "فضلہ",
  urbanization: "شہری کاری",
  population: "آبادی",
  global: "عالمی",
  warming: "گرمائش",
  emissions: "اخراج",
  gender: "جنس",
  equality: "برابری",
  child: "بچہ",
  labor: "مزدوری",
  employment: "ملازمت",
  rights: "حقوق",
  financial: "مالی",
  literacy: "خواندگی",
  understand: "سمجھنا",
  money: "پیسہ",
  manage: "انتظام کرنا",
  cryptocurrency: "کرپٹو کرنسی",
  secured: "محفوظ شدہ",
  cryptography: "کرپٹوگرافی",
  shares: "حصص",
  market: "مارکیٹ",
  mobile: "موبائل",
  applications: "ایپلیکیشنز",
  freelancing: "فری لانسنگ",
  working: "کام کرنا",
  companies: "کمپنیاں",
  startup: "اسٹارٹ اپ",
  innovation: "جدت",
  growth: "ترقی",
  fitness: "فٹنس",
  green: "سبز",
  architecture: "معماری",
  biotechnology: "بایوٹیکنالوجی",
  agriculture: "زراعت",
  recycling: "ری سائیکلنگ",
  environment: "ماحول",
  cloud: "کلاؤڈ",
  wearable: "پہنے جانے والے",
  monitor: "نگرانی کرنا",
  organs: "اعضاء",
  robotics: "روبوٹکس",
  build: "تعمیر کرنا",
  smart: "سمارٹ",
  cities: "شہر",
  governance: "حکمرانی",
  ethics: "اخلاقیات"
};

export function translateParagraph(text) {
  return text
    .split(/\s+/)
    .map((word) => dictionary[word.toLowerCase().replace(/[.,]/g, "")] || word)
    .join(" ");
}
